name: kabj_mobile
publish_to: 'none'
description: Estructura inicial de la app mÃ³vil.
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
